# Beryllium

#separator="ïŒƒ"
#separator_color="red"
#key_color="red"
prefer_small_ascii = false

spacing         = 3
hide_ascii      = true
key_color       = "#7067CF"
separator       = ""

[box]
title           = "î«“ Katana-GF66 "
border          = "plain"
visible         = true


[palette]
glyph           = "î®´  "
visible         = true

[bar]
glyph           = "â—‹"
hide_delimiters = true
visible         = true

[box.inner_margin]
x               = 2
y               = 1


[custom_ascii]
#color="red"
color           = "#94251e"
path="~/.config/macchina/themes/ubuntu.txt"

[keys]
host       =  "î™¦  host"
kernel     =  "ï˜  kernel"
distro     =  "\uf303  distro"
packages   =  "ó°—  packages"
terminal   =  "îˆ«  terminal"
shell      =  "î•  shell"
cpu        =  "ï‹›  cpu"
cpu_load   =  "î¿  cpu load"
memory     =  "ó°›  memory"
battery    =  "\uf240  battery"
disk_space =  "\uf0a0  disk"
uptime     =  "\ue641  uptime"
backlight  =  "ğŸ•¯ï¸ brightness"
de         =  "ğŸ’» de"
wm         =  "\uf2d2ğŸ—— wm"
